### ISSUE TITLE
Links in notifications do refer to the original/internal name not the currently accessed

### ISSUE THREAD

**Issue by DoerrSt** [nextcloud/notifications#54]
### Steps to reproduce
1. Install Nextcloud with a internal servername
2. Access Nextcloud via external servername 
3. Click on a link in a notification (e.g. updated component, add personal information, ...)

### Expected behaviour
I expect that the link works as all other links in Nextcloud the servername shouldn't be changed. 

### Actual behaviour
The link in the notification refers to the internal name which is not available from outside. 

### Server configuration
**Operating system**:
FreeNAS 9 Jail

**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
PHP 7.0

**Nextcloud version:** (see Nextcloud admin page)
11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
Downloaded from www.nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Activity  
Collaborative tags  
Comments  
Deleted files  
External sites  
External storage support  
Federation  
File access control  
File sharing  
Files automated tagging  
First run wizard  
Gallery  
Log Reader  
Nextcloud announcements  
Notifications  
Password policy  
PDF viewer  
Retention  
Server info  
Share by mail  
Text editor  
Theming  
Update notification  
Usage survey  
Versions  
Video player  
Announcement Center  
AppOrder  
Audio Player  
Bookmarks  
Calendar  
Collabora Online  
Contacts  
JavaScript XMPP Chat  
Keeweb  
Markdown Editor  
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => 'oc7eh0j412z1',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'nextcloud-1',
    1 => 'www.bla-2.de',
    2 => 'www.bla-1.de',
    3 => 'www.bla.de',
  ),
  'datadirectory' => '/mnt/Cloud/data',
  'overwrite.cli.url' => 'http://nextcloud-1',
  'dbtype' => 'mysql',
  'version' => '11.0.0.10',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud_admin',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/redis.sock',
    'port' => 0,
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_from_address' => '',
  'mail_domain' => '',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '',
  'mail_smtpport' => '',
  'mail_smtpsecure' => '',
  'mail_smtpname' => '',
  'mail_smtppassword' => ',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE 11.0.9600

**Operating system:**
Win 7

**Comment by nickvergessen** [comment]
I made PRs for the wrong notifications:

- [ ] "Fill out profile": https://github.com/nextcloud/firstrunwizard/issues/30
- [ ] "Send statistical info": https://github.com/nextcloud/survey_client/issues/46
- [ ] "You were mentioned in a comment": https://github.com/nextcloud/server/issues/2982
- [ ] "Update available": https://github.com/nextcloud/server/issues/2982

**Comment by nickvergessen** [comment]
I'll backport the stats and the profile thing, since they are triggered quite quickly after install and therefor suffer a bit more from this.
